# Generated by Django 5.0.2 on 2024-03-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.ImageField(default='media/static/default.jpg', upload_to='media/static'),
        ),
        migrations.AlterField(
            model_name='post',
            name='bio',
            field=models.CharField(default='No', max_length=200),
        ),
    ]
