# Generated by Django 5.0.2 on 2024-03-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_remove_post_post_post_pic_alter_post_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default='', upload_to='media/images')),
                ('bio', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='post',
        ),
    ]
