# Generated by Django 5.0.2 on 2024-03-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_posts_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default='', upload_to='media/images')),
                ('bio', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
